-- DDL script for database initialization.
-- Creates TARIFFS, CUSTOMERS, and MONTHLY_STATS tables.
-- Establishes Foreign Key relationships to ensure data integrity.

ALTER SESSION SET CURRENT_SCHEMA = SYSTEM;
CREATE TABLE TARIFFS (
    TARIFF_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    MONTHLY_FEE NUMBER,
    DATA_LIMIT NUMBER,
    MINUTE_LIMIT NUMBER,
    SMS_LIMIT NUMBER
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    CITY VARCHAR2(100),
    SIGNUP_DATE VARCHAR2(50), 
    TARIFF_ID NUMBER,
    CONSTRAINT fk_customer_tariff FOREIGN KEY (TARIFF_ID) REFERENCES TARIFFS(TARIFF_ID)
);

CREATE TABLE MONTHLY_STATS (
    ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    DATA_USAGE NUMBER(10,2),
    MINUTE_USAGE NUMBER,
    SMS_USAGE NUMBER,
    PAYMENT_STATUS VARCHAR2(20),
    CONSTRAINT fk_stats_customer FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);



-- Auto-inserting reference data for TARIFFS
INSERT INTO TARIFFS (TARIFF_ID, NAME, MONTHLY_FEE, DATA_LIMIT, MINUTE_LIMIT, SMS_LIMIT) 
VALUES (1, 'Genç Dinamik', 150, 10240, 600, 600);

INSERT INTO TARIFFS (TARIFF_ID, NAME, MONTHLY_FEE, DATA_LIMIT, MINUTE_LIMIT, SMS_LIMIT) 
VALUES (2, 'Kurumsal SMS', 1000, 0, 0, 10000);

INSERT INTO TARIFFS (TARIFF_ID, NAME, MONTHLY_FEE, DATA_LIMIT, MINUTE_LIMIT, SMS_LIMIT) 
VALUES (3, 'GB', 450, 20480, 1000, 250);

INSERT INTO TARIFFS (TARIFF_ID, NAME, MONTHLY_FEE, DATA_LIMIT, MINUTE_LIMIT, SMS_LIMIT) 
VALUES (4, 'Kobiye Destek', 350, 20480, 1000, 1000);

COMMIT;